### ISSUE TITLE
prepare the data

### ISSUE THREAD

**Issue by islamtashfiq** [divelab/icnn#1]
Can you mention the steps to provide the data?
Is there any specific preparation was made or not?

**Comment by HongyangGao** [comment]
Sure. The data downloaded from the offcial website should be written into a h5 file. The model will random crop the images in h5 file during training. For data augmentation, there should be one h5 file for each operation like rotation at a specific angle or horizontal flip. Put the file path into the train.txt or valid.txt so that the model know where to find them.

**Comment by islamtashfiq** [comment]
The data is in hdf format(https://cremi.org/static/data/sample_A_20160501.hdf). Do I need to load the images and their labels and save them in a h5 file. Also do I need to crop (change the dimension) of the dataset (from 1024x1024)?
Could you share your data preparation code as well?
Thanks

**Comment by HongyangGao** [comment]
Yes, you have to change the images and labels into a h5 file.
You don't have to crop to 1024x1024. For training, it doesn't matter, the trained image is about 256x256, which is randomly cropped from the original image. During prediction, you can change the dimension of input to your actual size. In my current setting, the prediction can not run on GPU due to memory limitation. I use CPU during prediction, whose time is about 30 minutes.

**Comment by islamtashfiq** [comment]
I made an h5 file from the original hdf but I get the below error
I0413 23:35:07.598784 12794 patch_sampler.cpp:398] label_shape0=256 input_shape_[i] =100
F0413 23:35:07.598795 12794 patch_sampler.cpp:399] Check failed: diff > 0 (-156 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f32dd1eadaa  (unknown)
    @     0x7f32dd1eace4  (unknown)
    @     0x7f32dd1ea6e6  (unknown)
    @     0x7f32dd1ed687  (unknown)
    @     0x7f32dd83c416  caffe::PatchCoordFinder<>::GetRandomPatchCenterCoord()
    @     0x7f32dd83d69f  caffe::PatchSampler<>::ReadOnePatch()
    @     0x7f32dd83e150  caffe::PatchSampler<>::patch_data_shape()
    @     0x7f32dd8eb1be  caffe::PatchDataLayer<>::DataLayerSetUp()
    @     0x7f32dd8e9ad3  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7f32dd98daa6  caffe::Net<>::Init()
    @     0x7f32dd98eb65  caffe::Net<>::Net()
    @     0x7f32dd94c6da  caffe::Solver<>::InitTrainNet()
    @     0x7f32dd94d7dc  caffe::Solver<>::Init()
    @     0x7f32dd94dae9  caffe::Solver<>::Solver()
    @     0x7f32dd966ff3  caffe::Creator_SGDSolver<>()
    @           0x40e81e  caffe::SolverRegistry<>::CreateSolver()
    @           0x407a9b  train()
    @           0x405891  main
    @     0x7f32dc4f8f45  (unknown)
    @           0x405fa1  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by HongyangGao** [comment]
It seems that the label shape is not the same to the shape of the image.

**Comment by islamtashfiq** [comment]
but it's the same I think
I0413 23:35:06.654935 12794 hdf5.cpp:35] Datatype class: H5T_INTEGER
I0413 23:35:07.598569 12794 data_provider.cpp:108] d_size =3
I0413 23:35:07.598593 12794 data_provider.cpp:111] loaded data shape : 100
I0413 23:35:07.598619 12794 data_provider.cpp:111] loaded data shape : 1250
I0413 23:35:07.598626 12794 data_provider.cpp:111] loaded data shape : 1250
I0413 23:35:07.598629 12794 data_provider.cpp:113]  
I0413 23:35:07.598633 12794 data_provider.cpp:115] loaded label shape : 100
I0413 23:35:07.598635 12794 data_provider.cpp:115] loaded label shape : 1250
I0413 23:35:07.598639 12794 data_provider.cpp:115] loaded label shape : 1250
I0413 23:35:07.598731 12794 data_provider.cpp:144] d_size =5
I0413 23:35:07.598737 12794 data_provider.cpp:147] data shape after prependig : 1
I0413 23:35:07.598738 12794 data_provider.cpp:147] data shape after prependig : 1
I0413 23:35:07.598740 12794 data_provider.cpp:147] data shape after prependig : 100
I0413 23:35:07.598742 12794 data_provider.cpp:147] data shape after prependig : 1250
I0413 23:35:07.598745 12794 data_provider.cpp:147] data shape after prependig : 1250
I0413 23:35:07.598749 12794 data_provider.cpp:149]  
I0413 23:35:07.598752 12794 data_provider.cpp:151] label shape after prependig  : 1
I0413 23:35:07.598755 12794 data_provider.cpp:151] label shape after prependig  : 1
I0413 23:35:07.598759 12794 data_provider.cpp:151] label shape after prependig  : 100
I0413 23:35:07.598762 12794 data_provider.cpp:151] label shape after prependig  : 1250
I0413 23:35:07.598767 12794 data_provider.cpp:151] label shape after prependig  : 1250
I0413 23:35:07.598770 12794 data_provider.cpp:175] loaded hdf5 file /home/ali/projects/cremi_python/cremi_train.h5
I0413 23:35:07.598784 12794 patch_sampler.cpp:398] label_shape0=256 input_shape_[i] =100

**Comment by HongyangGao** [comment]
both data and label should have four dimension. It may be this problem.

**Comment by islamtashfiq** [comment]
I think there is something wrong with the patch sampler, since it needs a label shape with size 256. I think there should be some cropping involved.
Could you please share your data generation code?

**Comment by HongyangGao** [comment]
Did you install the caffe in this project. The patch sampler is written in this specific caffe.

**Comment by islamtashfiq** [comment]
I installed it, I think there is nothing wrong with caffe. Maybe the data generation code (h5 from hdf) would clarify this.

**Comment by HongyangGao** [comment]
Actually I don't have the code for generating H5 file. One student in our lab did this. The data format should be (B, H, W, C). Channel should be in the last dimension.

**Comment by islamtashfiq** [comment]
so the input that is created from hdf file should have the size(100,1250,1250,1), right?
After that what will happen in prepending?
I got this error, after changing the shape...

I0419 11:44:32.733446 21196 patch_sampler.cpp:121] loading batch patch_count = 0
I0419 11:44:32.734104 21196 hdf5.cpp:35] Datatype class: H5T_INTEGER
I0419 11:44:32.734160 21201 patch_sampler.cpp:315] phase =train and solover_count =1
I0419 11:44:32.734170 21201 patch_sampler.cpp:319] solver_count  = 1  size of queue pairs = 1
I0419 11:44:32.734176 21201 patch_sampler.cpp:323] size of queue  is now = 0
I0419 11:44:33.611358 21196 data_provider.cpp:108] d_size =4
I0419 11:44:33.611382 21196 data_provider.cpp:111] loaded data shape : 100
I0419 11:44:33.611405 21196 data_provider.cpp:111] loaded data shape : 1250
I0419 11:44:33.611407 21196 data_provider.cpp:111] loaded data shape : 1250
I0419 11:44:33.611409 21196 data_provider.cpp:111] loaded data shape : 1
I0419 11:44:33.611412 21196 data_provider.cpp:113]  
I0419 11:44:33.611418 21196 data_provider.cpp:115] loaded label shape : 100
I0419 11:44:33.611419 21196 data_provider.cpp:115] loaded label shape : 1250
I0419 11:44:33.611421 21196 data_provider.cpp:115] loaded label shape : 1250
I0419 11:44:33.611423 21196 data_provider.cpp:115] loaded label shape : 1
I0419 11:44:33.611516 21196 data_provider.cpp:144] d_size =5
I0419 11:44:33.611521 21196 data_provider.cpp:147] data shape after prependig : 1
I0419 11:44:33.611523 21196 data_provider.cpp:147] data shape after prependig : 100
I0419 11:44:33.611526 21196 data_provider.cpp:147] data shape after prependig : 1250
I0419 11:44:33.611527 21196 data_provider.cpp:147] data shape after prependig : 1250
I0419 11:44:33.611529 21196 data_provider.cpp:147] data shape after prependig : 1
I0419 11:44:33.611531 21196 data_provider.cpp:149]  
I0419 11:44:33.611532 21196 data_provider.cpp:151] label shape after prependig  : 1
I0419 11:44:33.611534 21196 data_provider.cpp:151] label shape after prependig  : 100
I0419 11:44:33.611536 21196 data_provider.cpp:151] label shape after prependig  : 1250
I0419 11:44:33.611538 21196 data_provider.cpp:151] label shape after prependig  : 1250
I0419 11:44:33.611541 21196 data_provider.cpp:151] label shape after prependig  : 1
I0419 11:44:33.611542 21196 data_provider.cpp:175] loaded hdf5 file /home/projects/cremi_python/cremi_train.h5
F0419 11:44:33.611564 21196 data_transformerND.cpp:28] Check failed: input_channels == 1 (100 vs. 1)

**Comment by HongyangGao** [comment]
The error means the channel num is 100 not 1. You can check the dims of h5.

**Comment by islamtashfiq** [comment]
Can you share the train and validation h5 file? It seems that my ordering is correct but something is wrong with the inner code...

**Comment by HongyangGao** [comment]
I can. But the original file is too large. I may slice some pieces from the original data.

**Comment by islamtashfiq** [comment]
Could you share it on dropbox?

**Comment by HongyangGao** [comment]
Sure. Can you give me several days since I am in my final weeks of spring semester?
